spring:
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev
  application:
    name: data-generator-data    # 注册到Eureka的服务ID
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://172.16.160.61:3306/data_generator
    username: root
    password: root
    filter: stat,wall,log4j
    dbcp2:  # 进行数据库连接池的配置
      min-idle: 5                   # 数据库连接池的最小维持连接数
      initial-size: 5                 # 初始化连接数
      max-total: 5                    # 最大连接数
      max-wait-millis: 200                # 等待连接获取的最大超时时间
      validationQuery: SELECT 'x' from dual
feign:
  hystrix:
    enabled: true    # 开启Feign的Hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka    # Eureka服务地址
  instance:
    instance-id: data-generator-data:8081    # 注册到Eureka服务的实例名称
    prefer-ip-address: true     # 在Eureka服务列表中以IP地址记录
    lease-renewal-interval-in-seconds: 3    # client发送心跳给Eureka的频率 3秒
    lease-expiration-duration-in-seconds: 10    # client发送心跳给Eureka的超时时间 10秒
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
