server:
  port: 9501
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: data-generator-gateway:9501
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
spring:
  application:
    name: data-generator-gateway
zuul:
  prefix: /data-generator
  ignored-services: "*"
  routes:
    data-generator-data: /data-proxy/** 
    data-generator-task: /task-proxy/** 