spring:
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev
  application:
    name: data-generator-gateway
zuul:
  prefix: /data-generator
  ignored-services: "*"
  routes:
    data-generator-data: /data-proxy/** 
    data-generator-task: /task-proxy/** 
    
