spring:
  profiles:
    active:
    - dev
---
spring: 
  profiles: dev
  application:
    name: data-generator-manage
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://172.16.160.61:3306/data_generator
    username: root
    password: root
    filter: stat,wall,log4j
    dbcp2:  # 进行数据库连接池的配置
      min-idle: 5                   # 数据库连接池的最小维持连接数
      initial-size: 5                 # 初始化连接数
      max-total: 5                    # 最大连接数
      max-wait-millis: 200                # 等待连接获取的最大超时时间
      validationQuery: SELECT 'x' from dual


server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka    # Eureka服务地址
    register-with-eureka: true    # 注册到Eureka中
    fetch-registry: true    # 从Eureka中获取服务注册信息
  instance:
    instance-id: data-generator-manage:8082    # 注册到Eureka服务的实例名称
    prefer-ip-address: true    # 在Eureka服务列表中以IP地址记录

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: cn.com.yoyosys.datagenerator.task.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
info:    # 配置属性
  app.name: data-generator-manage
  company.name: www.yoyosys.com.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
